application: evolvethefuture
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: compiled/evolve/

- url: /fragments/(.*\.html)
  static_files: compiled/evolve/fragments/\1
  upload: compiled/evolve/fragments/(.*\.html)

- url: /robots.txt
  static_files: compiled/evolve/robots.txt
  upload: compiled/evolve/robots.txt

- url: /favicon.ico
  static_files: compiled/evolve/image/favicon.gif
  upload: compiled/evolve/images/favicon.ico

- url: /.*
  script: common/appenginepatch/main.py

skip_files: |
  ^(.*/)?(
  (app\.yaml)|
  (app\.yml)|
  (index\.yaml)|
  (index\.yml)|
  (#.*#)|
  (.*~)|
  (.*\.py[co])|
  (.*/RCS/.*)|
  (\..*)|
  )$|
  ^(
  (common/zip-packages/django/.*)|
  (compiled/.*LICENSE)|
  (compiled/.*README)|
  (compiled/evolve/dijit/(_base|_editor|_tree|form|layout|nls)/.*)|
  (compiled/.*/soria/.*)|
  (compiled/.*/nihilo/.*)|
  (compiled/evolve/doh/.*)|
  (compiled/evolve/dojo/(_base|cldr|data|date|dnd|fx|io|rpc)/.*)|
  (compiled/evolve/dojox/.*)|
  (compiled/evolve/test/.*)|
  (compiled/evolve/util/.*)|
  )$