// Generated by CoffeeScript 1.4.0
(function() {

  CORE.data = {
    SPECIES_URL: "/data/species/",
    CPUTIME_URL: "/data/cputime/",
    saveSpecies: function(species) {
      var postData;
      postData = {
        code: CORE.assembler.convertCodeToString(species.code),
        name: species.name,
        count: species.count - species.sentCount
      };
      if (species.getParent() != null) {
        postData.parentRef = species.getParent().pk;
      }
      return $.post(this.SPECIES_URL, postData).done(function(data) {
        species.pk = data[0].pk;
        return species.displayName = data[0].fields.uniqueName;
      });
    },
    putScore: function(species, score) {
      species.scoreList.push(score);
      return $.get("" + this.SPECIES_URL + "addScore/" + species.pk + "/?score=" + score);
    },
    putCpuTime: function(amount) {
      return $.post(this.CPUTIME_URL, {
        time: amount
      });
    },
    getSingleSpecies: function(id, callback) {
      return $.getJSON("" + this.SPECIES_URL + "id/" + id + "/", callback);
    },
    getSpecies: function(count) {
      return $.getJSON("" + this.SPECIES_URL + "list/0/" + count);
    },
    getChildrenOfSpecies: function(id, callback) {
      return $.getJSON("" + this.SPECIES_URL + "children/" + id + "/", callback);
    },
    getUserProfile: function() {
      return $.get("/data/user/id/0");
    }
  };

}).call(this);
