// Generated by CoffeeScript 1.4.0
(function() {

  CORE.staticpage = {
    initialise: function() {
      return CORE.util.getUserProfile();
    }
  };

  $(document).ready($.proxy(CORE.staticpage.initialise, CORE.staticpage));

}).call(this);
