// Generated by CoffeeScript 1.4.0
(function() {

  CORE.util = {
    MAXHASHCHECK: 50,
    getHashCode: function(memory) {
      var hash, ii, maxcheck, op, _i, _len;
      hash = 0;
      maxcheck = CORE.util.MAXHASHCHECK;
      for (ii = _i = 0, _len = memory.length; _i < _len; ii = ++_i) {
        op = memory[ii];
        if (ii < maxcheck) {
          hash += op * ii;
        }
      }
      return hash;
    },
    getUserProfile: function() {
      return CORE.data.getUserProfile().done(function(userProfile) {
        CORE.userProfile = userProfile;
        if (CORE.userProfile == null) {
          $("#logoutLink").hide();
          return $("#loginLink").show();
        } else {
          $("#username").html(CORE.userProfile.username);
          $("#logoutLink").show();
          return $("#loginLink").hide();
        }
      });
    }
  };

}).call(this);
