// Generated by CoffeeScript 1.4.0
(function() {

  CORE.util = {
    MAXHASHCHECK: 50,
    getHashCode: function(memory) {
      var hash, ii, maxcheck;
      hash = 0;
      maxcheck = CORE.util.MAXHASHCHECK;
      ii = 0;
      while (ii < memory.length && ii < maxcheck) {
        hash += memory[ii] * ii;
        ii += 1;
      }
      return hash;
    },
    getUserProfile: function() {
      return CORE.data.getUserProfile(function(userProfile) {
        CORE.userProfile = userProfile;
        if (CORE.userProfile === null) {
          $("#logoutLink").hide();
          return $("#loginLink").show();
        } else {
          $("#username").html(CORE.userProfile.username);
          $("#logoutLink").show();
          return $("#loginLink").hide();
        }
      });
    }
  };

}).call(this);
